/* tslint:disable */
/* eslint-disable */
/**
 * PK.PHCalc.OutsourcingDummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    FreightDTO,
    FreightDTOFromJSON,
    FreightDTOToJSON,
} from '../models';

export interface FreightUpdateRequest {
    model: Array<FreightDTO>;
}

/**
 * 
 */
export class FreightApi extends runtime.BaseAPI {

    /**
     */
    async freightGetRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<FreightDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/freight`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(FreightDTOFromJSON));
    }

    /**
     */
    async freightGet(initOverrides?: RequestInit): Promise<Array<FreightDTO>> {
        const response = await this.freightGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async freightUpdateRaw(requestParameters: FreightUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<object>> {
        if (requestParameters.model === null || requestParameters.model === undefined) {
            throw new runtime.RequiredError('model','Required parameter requestParameters.model was null or undefined when calling freightUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/freight`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters.model.map(FreightDTOToJSON),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async freightUpdate(requestParameters: FreightUpdateRequest, initOverrides?: RequestInit): Promise<object> {
        const response = await this.freightUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
