/* tslint:disable */
/* eslint-disable */
/**
 * PK.PHCalc.OutsourcingDummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Bounds
 */
export interface Bounds {
    /**
     * 
     * @type {number}
     * @memberof Bounds
     */
    minimum?: number;
    /**
     * 
     * @type {number}
     * @memberof Bounds
     */
    maximum?: number;
}

export function BoundsFromJSON(json: any): Bounds {
    return BoundsFromJSONTyped(json, false);
}

export function BoundsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Bounds {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'minimum': !exists(json, 'Minimum') ? undefined : json['Minimum'],
        'maximum': !exists(json, 'Maximum') ? undefined : json['Maximum'],
    };
}

export function BoundsToJSON(value?: Bounds | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Minimum': value.minimum,
        'Maximum': value.maximum,
    };
}

