/* tslint:disable */
/* eslint-disable */
/**
 * PK.PHCalc.OutsourcingDummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MachineSummaryDTO
 */
export interface MachineSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof MachineSummaryDTO
     */
    name: string;
}

export function MachineSummaryDTOFromJSON(json: any): MachineSummaryDTO {
    return MachineSummaryDTOFromJSONTyped(json, false);
}

export function MachineSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MachineSummaryDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['Name'],
    };
}

export function MachineSummaryDTOToJSON(value?: MachineSummaryDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Name': value.name,
    };
}

