/* tslint:disable */
/* eslint-disable */
/**
 * PK.PHCalc.OutsourcingDummy
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrintColorCharge
 */
export interface PrintColorCharge {
    /**
     * 
     * @type {number}
     * @memberof PrintColorCharge
     */
    count?: number;
    /**
     * 
     * @type {number}
     * @memberof PrintColorCharge
     */
    price?: number;
}

export function PrintColorChargeFromJSON(json: any): PrintColorCharge {
    return PrintColorChargeFromJSONTyped(json, false);
}

export function PrintColorChargeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrintColorCharge {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'Count') ? undefined : json['Count'],
        'price': !exists(json, 'Price') ? undefined : json['Price'],
    };
}

export function PrintColorChargeToJSON(value?: PrintColorCharge | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'Count': value.count,
        'Price': value.price,
    };
}

